name: rustfmt

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: rustfmt
      run: cargo fmt -- --check
