name: Warnings

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    
    container:
      image: rustlang/rust:nightly-buster-slim rust:nightly-buster-slim

    steps:
    - uses: actions/checkout@v2

    - name: Warnings
      run: cargo check

    - name: rustfmt
      run: cargo fmt -- --check
